if(NOT DEFINED ARCHIVER OR NOT DEFINED OUTPUT OR NOT DEFINED INPUTS)
    message(FATAL_ERROR "ARCHIVER, OUTPUT, and INPUTS are required")
endif()

string(REPLACE "|" ";" INPUT_ARCHIVES "${INPUTS}")
set(MRI_FILE "${OUTPUT}.mri")
file(WRITE "${MRI_FILE}" "CREATE ${OUTPUT}\n")
foreach(INPUT_ARCHIVE IN LISTS INPUT_ARCHIVES)
    file(APPEND "${MRI_FILE}" "ADDLIB ${INPUT_ARCHIVE}\n")
endforeach()
file(APPEND "${MRI_FILE}" "SAVE\nEND\n")

file(REMOVE "${OUTPUT}")
execute_process(
    COMMAND "${ARCHIVER}" -M
    INPUT_FILE "${MRI_FILE}"
    COMMAND_ERROR_IS_FATAL ANY
)
file(REMOVE "${MRI_FILE}")
